
version: '3.8'
services:
  app:
    image: python:3.10-slim
    container_name: fastapi_app
    working_dir: /code
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: uvicorn src.API:app --host 0.0.0.0 --port 8000
